-- @CREATE_LISTS
CREATE TABLE IF NOT EXISTS TODOLISTS
(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NAME TEXT NOT NULL);

-- @CREATE_CASES
CREATE TABLE IF NOT EXISTS CASES
(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
DESCRIPTION TEXT NOT NULL,
LISTID INTEGER,
FOREIGN KEY (LISTID) REFERENCES TODOLISTS (ID));

-- @ADD_LIST
INSERT INTO TODOLISTS (NAME) VALUES ("{{name}}");

-- @DELETE_LIST
DELETE FROM TODOLISTS WHERE id = {{id}};

-- @DELETE_CASE_BY_LIST
DELETE FROM CASES WHERE listId = {{id}};

-- @ADD_CASE
INSERT INTO CASES (description, listId) VALUES ("{{description}}", {{listId}});

-- @DELETE_CASE
DELETE FROM CASES WHERE id = {{id}};

-- @SHOW_LISTS
SELECT * FROM TODOLISTS;

-- @SHOW_CASES_OF_LIST
SELECT * FROM CASES WHERE listId = {{id}}